package cmk

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/BurntSushi/toml"
)

const lockFileName = "cmk.lock"

// Lock pins the resolved inputs that cmk.yaml leaves floating: each
// platform's exact toolchain release and the commit behind each git dep ref.
type Lock struct {
	Schema     int                       `toml:"schema"`
	Toolchain  LockToolchain             `toml:"toolchain,omitempty"`
	Toolchains map[string]*LockToolchain `toml:"toolchains,omitempty"`
	Deps       map[string]*LockDep       `toml:"deps"`
	dirty      bool
}

type LockToolchain struct {
	Selector       string `toml:"selector,omitempty"`
	Target         string `toml:"target,omitempty"`
	ManifestSHA256 string `toml:"manifest_sha256,omitempty"`
	ArtifactSHA256 string `toml:"artifact_sha256,omitempty"`
}

type LockDep struct {
	Git    string `toml:"git,omitempty"`
	Ref    string `toml:"ref,omitempty"`
	Commit string `toml:"commit,omitempty"`
	// Stamp is the dep's content hash, which keys its store entry.
	// Pinned here so build/run/env resolve store paths without
	// recomputing stamps (and so the entry a build dir was configured
	// against survives cmk.yaml edits until the next sync).
	Stamp  string            `toml:"stamp,omitempty"`
	Stamps map[string]string `toml:"stamps,omitempty"`
}

func loadLock(root string) (*Lock, error) {
	lk := &Lock{Schema: 2, Toolchains: map[string]*LockToolchain{}, Deps: map[string]*LockDep{}}
	data, err := os.ReadFile(filepath.Join(root, lockFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return lk, nil
		}
		return nil, err
	}
	if _, err := toml.Decode(string(data), lk); err != nil {
		return nil, fmt.Errorf("%s: %w", lockFileName, err)
	}
	if lk.Schema > 2 {
		return nil, fmt.Errorf("%s has schema %d; this cmk only understands 2 (upgrade cmk)", lockFileName, lk.Schema)
	}
	if lk.Schema < 2 {
		lk.dirty = true
	}
	if lk.Toolchains == nil {
		lk.Toolchains = map[string]*LockToolchain{}
	}
	platformAliases := map[string]string{}
	for name, pin := range lk.Toolchains {
		if name != "linux" && name != "macos" {
			continue
		}
		canonical := platformForTarget(pin.Target)
		if canonical == "" {
			continue
		}
		platformAliases[name] = canonical
		if lk.Toolchains[canonical] == nil {
			lk.Toolchains[canonical] = pin
		}
		delete(lk.Toolchains, name)
		lk.dirty = true
	}
	if !lk.Toolchain.empty() {
		platform := platformForTarget(lk.Toolchain.Target)
		if platform == "" {
			platform = hostPlatform(runtime.GOOS, runtime.GOARCH)
		}
		if lk.Toolchains[platform] == nil {
			pin := lk.Toolchain
			lk.Toolchains[platform] = &pin
		}
		lk.Toolchain = LockToolchain{}
	}
	if lk.Deps == nil {
		lk.Deps = map[string]*LockDep{}
	}
	for _, dep := range lk.Deps {
		if dep.Stamps == nil {
			dep.Stamps = map[string]string{}
		}
		for alias, canonical := range platformAliases {
			if dep.Stamps[alias] != "" && dep.Stamps[canonical] == "" {
				dep.Stamps[canonical] = dep.Stamps[alias]
			}
			if _, ok := dep.Stamps[alias]; ok {
				delete(dep.Stamps, alias)
				lk.dirty = true
			}
		}
		if dep.Stamp != "" {
			platform := hostPlatform(runtime.GOOS, runtime.GOARCH)
			if len(lk.Toolchains) == 1 {
				for name := range lk.Toolchains {
					platform = name
				}
			}
			if dep.Stamps[platform] == "" {
				dep.Stamps[platform] = dep.Stamp
			}
			dep.Stamp = ""
			lk.dirty = true
		}
	}
	return lk, nil
}

func saveLock(root string, lk *Lock) error {
	lk.Schema = 2
	lk.Toolchain = LockToolchain{}
	for _, dep := range lk.Deps {
		dep.Stamp = ""
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by cmk. Commit this file.\n")
	if err := toml.NewEncoder(&buf).Encode(lk); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, lockFileName), buf.Bytes(), 0o644); err != nil {
		return err
	}
	lk.dirty = false
	return nil
}

func (pin LockToolchain) empty() bool {
	return pin.Selector == "" && pin.Target == "" && pin.ManifestSHA256 == "" && pin.ArtifactSHA256 == ""
}

func hostPlatform(goos, goarch string) string {
	osName := goos
	if osName == "darwin" {
		osName = "macos"
	}
	arch := goarch
	switch arch {
	case "amd64":
		arch = "x86_64"
	case "arm64":
		arch = "aarch64"
	}
	return osName + "-" + arch
}

func platformForTarget(target string) string {
	switch {
	case strings.Contains(target, "apple-darwin"):
		return "macos-aarch64"
	case strings.HasPrefix(target, "x86_64-") && strings.Contains(target, "linux"):
		return "linux-x86_64"
	case strings.HasPrefix(target, "aarch64-") && strings.Contains(target, "linux"):
		return "linux-aarch64"
	case strings.Contains(target, "linux"):
		return "linux-unknown"
	default:
		return ""
	}
}

func (lk *Lock) toolchainFor(goos, goarch string) *LockToolchain {
	if lk.Toolchains == nil {
		lk.Toolchains = map[string]*LockToolchain{}
	}
	platform := hostPlatform(goos, goarch)
	if lk.Toolchains[platform] == nil {
		lk.Toolchains[platform] = &LockToolchain{}
	}
	return lk.Toolchains[platform]
}

func (dep *LockDep) stampFor(goos, goarch string) string {
	if dep == nil {
		return ""
	}
	return dep.Stamps[hostPlatform(goos, goarch)]
}

func (dep *LockDep) setStampFor(goos, goarch, stamp string) {
	if dep.Stamps == nil {
		dep.Stamps = map[string]string{}
	}
	dep.Stamps[hostPlatform(goos, goarch)] = stamp
}
