package cmk

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

const lockFileName = "cmk.lock"

// Lock pins the resolved inputs that cmk.toml leaves floating: the
// exact toolchain release and the commit behind each git dep ref.
type Lock struct {
	Schema    int                 `toml:"schema"`
	Toolchain LockToolchain       `toml:"toolchain"`
	Deps      map[string]*LockDep `toml:"deps"`
}

type LockToolchain struct {
	Selector       string `toml:"selector,omitempty"`
	Target         string `toml:"target,omitempty"`
	ManifestSHA256 string `toml:"manifest_sha256,omitempty"`
	ArtifactSHA256 string `toml:"artifact_sha256,omitempty"`
}

type LockDep struct {
	Git    string `toml:"git,omitempty"`
	Ref    string `toml:"ref,omitempty"`
	Commit string `toml:"commit,omitempty"`
	// Stamp is the dep's content hash, which keys its store entry.
	// Pinned here so build/run/env resolve store paths without
	// recomputing stamps (and so the entry a build dir was configured
	// against survives cmk.toml edits until the next sync).
	Stamp string `toml:"stamp,omitempty"`
}

func loadLock(root string) (*Lock, error) {
	lk := &Lock{Schema: 1, Deps: map[string]*LockDep{}}
	data, err := os.ReadFile(filepath.Join(root, lockFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return lk, nil
		}
		return nil, err
	}
	if _, err := toml.Decode(string(data), lk); err != nil {
		return nil, fmt.Errorf("%s: %w", lockFileName, err)
	}
	if lk.Schema > 1 {
		return nil, fmt.Errorf("%s has schema %d; this cmk only understands 1 (upgrade cmk)", lockFileName, lk.Schema)
	}
	if lk.Deps == nil {
		lk.Deps = map[string]*LockDep{}
	}
	return lk, nil
}

func saveLock(root string, lk *Lock) error {
	lk.Schema = 1
	var buf bytes.Buffer
	buf.WriteString("# Generated by cmk. Commit this file.\n")
	if err := toml.NewEncoder(&buf).Encode(lk); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(root, lockFileName), buf.Bytes(), 0o644)
}
