package cmk

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const configFlagsFileRel = ".cache/cmk/configurations.cmake"

var configNameRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]*$`)

var standardConfigs = []string{"Debug", "Release", "RelWithDebInfo", "MinSizeRel"}

func effectiveGenerator(cfg *Config, preset *PresetCfg) string {
	if preset != nil && preset.Generator != "" {
		return preset.Generator
	}
	if cfg.Configure.Generator != "" {
		return cfg.Configure.Generator
	}
	return "Ninja"
}

func isMultiConfigGenerator(generator string) bool {
	return strings.Contains(generator, "Multi-Config") ||
		strings.HasPrefix(generator, "Visual Studio") ||
		generator == "Xcode"
}

func isMultiConfig(cfg *Config, preset *PresetCfg) bool {
	return isMultiConfigGenerator(effectiveGenerator(cfg, preset))
}

func hasMultiConfigPreset(cfg *Config) bool {
	for _, preset := range cfg.Configure.Presets {
		if isMultiConfig(cfg, preset) {
			return true
		}
	}
	return false
}

func isStandardConfig(name string) bool {
	for _, configuration := range standardConfigs {
		if strings.EqualFold(configuration, name) {
			return true
		}
	}
	return false
}

func configuredConfigurations(cfg *Config) []string {
	names := make([]string, 0, len(cfg.Configure.Configurations))
	for _, configuration := range cfg.Configure.Configurations {
		if configuration != nil {
			names = append(names, configuration.Name)
		}
	}
	return names
}

func effectiveConfigurations(cfg *Config, preset *PresetCfg) []string {
	if preset != nil && preset.Configurations != nil {
		return append([]string(nil), preset.Configurations...)
	}
	return configuredConfigurations(cfg)
}

func effectiveDefaultConfiguration(cfg *Config, preset *PresetCfg) string {
	if preset != nil && preset.DefaultConfiguration != "" {
		return preset.DefaultConfiguration
	}
	configurations := effectiveConfigurations(cfg, preset)
	for _, configuration := range configurations {
		if configuration == cfg.Configure.DefaultConfiguration {
			return configuration
		}
	}
	if len(configurations) > 0 {
		return configurations[0]
	}
	return ""
}

func (p *Project) resolveConfig(preset *PresetCfg, explicit string) (string, error) {
	if !isMultiConfig(p.Cfg, preset) {
		if explicit != "" {
			return "", fmt.Errorf("--config %q requires a multi-config generator", explicit)
		}
		return "", nil
	}
	configurations := effectiveConfigurations(p.Cfg, preset)
	if explicit == "" {
		return effectiveDefaultConfiguration(p.Cfg, preset), nil
	}
	for _, configuration := range configurations {
		if configuration == explicit {
			return explicit, nil
		}
	}
	return "", fmt.Errorf("configuration %q not found (known: %s)", explicit, strings.Join(configurations, ", "))
}

// resolveVariant selects a managed preset and an optional multi-config
// configuration. Without cmk.yaml it selects an existing foreign CMake build
// tree and passes --config through unchanged.
func (p *Project) resolveVariant(buildDir, presetName, configName string) (dir, configuration string, err error) {
	if !p.hasCmkConfig() {
		if presetName != "" {
			return "", "", fmt.Errorf("--preset requires a cmk.yaml project")
		}
		dir, err = p.resolveBuildDir(buildDir)
		return dir, configName, err
	}
	if buildDir != "" && presetName != "" {
		return "", "", fmt.Errorf("pass either --build <dir> or --preset <preset>, not both")
	}
	var preset *PresetCfg
	if buildDir != "" {
		dir, err = p.resolveBuildDir(buildDir)
	} else {
		var presetErr error
		preset, presetErr = resolvePreset(p.Cfg, presetName)
		if presetErr != nil {
			return "", "", presetErr
		}
		dir = presetBuildDir(p, preset)
	}
	if err != nil {
		return "", "", err
	}
	if preset == nil {
		preset = presetForDir(p, dir)
	}
	configuration, err = p.resolveConfig(preset, configName)
	return dir, configuration, err
}

// configFlagsFile computes the CMake project include that initializes custom
// or extended multi-config flags. Entries are emitted in inheritance order.
func configFlagsFile(p *Project) (path, content string) {
	path = filepath.Join(p.Root, filepath.FromSlash(configFlagsFileRel))
	if len(p.Cfg.Configure.Configurations) == 0 {
		return path, ""
	}
	edits := orderedConfigurationEdits(p.Cfg)
	if len(edits) == 0 {
		return path, ""
	}
	var builder strings.Builder
	builder.WriteString("# Generated by cmk from cmk.yaml.\n\n")
	builder.WriteString("function(cmk_set_config_flag var base suffix desc)\n")
	builder.WriteString("  set(orig_var \"CMK_ORIGINAL_${var}\")\n")
	builder.WriteString("  if(NOT DEFINED ${orig_var})\n")
	builder.WriteString("    set(${orig_var} \"${${var}}\" CACHE INTERNAL \"cmk original ${var}\")\n")
	builder.WriteString("  endif()\n")
	builder.WriteString("  if(NOT \"${base}\" STREQUAL \"\")\n")
	builder.WriteString("    set(value \"${${base}}\")\n")
	builder.WriteString("  else()\n")
	builder.WriteString("    set(value \"${${orig_var}}\")\n")
	builder.WriteString("  endif()\n")
	builder.WriteString("  string(STRIP \"${value} ${suffix}\" value)\n")
	builder.WriteString("  set(${var} \"${value}\" CACHE STRING \"${desc}\" FORCE)\n")
	builder.WriteString("endfunction()\n\n")
	vars := p.vars()
	for _, configuration := range edits {
		name := strings.ToUpper(configuration.Name)
		base := strings.ToUpper(configuration.Inherits)
		compile := expandFlagList(configuration.Compile, vars)
		cflags := joinFlags(compile, expandFlagList(configuration.C, vars))
		cxxflags := joinFlags(compile, expandFlagList(configuration.CXX, vars))
		link := expandFlagList(configuration.Link, vars)
		writeConfigFlag(&builder, "CMAKE_C_FLAGS_"+name, configBase("CMAKE_C_FLAGS_", base), cflags, configuration.Name+" C flags")
		writeConfigFlag(&builder, "CMAKE_CXX_FLAGS_"+name, configBase("CMAKE_CXX_FLAGS_", base), cxxflags, configuration.Name+" C++ flags")
		for _, kind := range []string{"EXE", "SHARED", "MODULE"} {
			prefix := "CMAKE_" + kind + "_LINKER_FLAGS_"
			writeConfigFlag(&builder, prefix+name, configBase(prefix, base), link, configuration.Name+" "+strings.ToLower(kind)+" linker flags")
		}
		builder.WriteByte('\n')
	}
	return path, builder.String()
}

func orderedConfigurationEdits(cfg *Config) []*ConfigurationCfg {
	byName := cfg.Configure.configurationByName
	var ordered []*ConfigurationCfg
	visited := map[string]bool{}
	var visit func(*ConfigurationCfg)
	visit = func(configuration *ConfigurationCfg) {
		if configuration == nil || visited[configuration.Name] {
			return
		}
		if base := byName[configuration.Inherits]; base != nil {
			visit(base)
		}
		visited[configuration.Name] = true
		if configuration.Inherits != "" || len(configuration.Compile) > 0 || len(configuration.C) > 0 || len(configuration.CXX) > 0 || len(configuration.Link) > 0 {
			ordered = append(ordered, configuration)
		}
	}
	for _, configuration := range cfg.Configure.Configurations {
		visit(configuration)
	}
	return ordered
}

func configBase(prefix, base string) string {
	if base == "" {
		return ""
	}
	return prefix + base
}

func expandFlagList(flags []string, vars map[string]string) string {
	expanded := make([]string, 0, len(flags))
	for _, flag := range flags {
		if flag = strings.TrimSpace(expandVars(flag, vars)); flag != "" {
			expanded = append(expanded, flag)
		}
	}
	return strings.Join(expanded, " ")
}

func writeConfigFlag(builder *strings.Builder, variable, base, suffix, description string) {
	fmt.Fprintf(builder, "cmk_set_config_flag(%s %s %s %s)\n", variable, cmakeQuote(base), cmakeQuote(suffix), cmakeQuote("cmk: "+description))
}

func writeConfigFlagsFile(p *Project) error {
	path, content := configFlagsFile(p)
	if content == "" {
		os.Remove(path)
		return nil
	}
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, []byte(content)) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func cmakeQuote(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `"`, `\"`)
	return `"` + value + `"`
}

func joinFlags(parts ...string) string {
	var values []string
	for _, part := range parts {
		if part = strings.TrimSpace(part); part != "" {
			values = append(values, part)
		}
	}
	return strings.Join(values, " ")
}
